---
- name: Validate chkconfig
  command: chkconfig {{ item }} on
  with_items:
    - nginx
    - mysqld
    - php-fpm

- name: Start service
  service: name={{ item }} state=started
  with_items:
    - nginx
    - mysqld
    - php-fpm
